remote_theme: knhash/jekyllBear
title: 鵝庵筆記
description: 一些讀書筆記。
author: 鵝庵
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
# baseurl: "/jekyllBear" # the subpath of your site, e.g. /blog/
url: "https://seeking-darkness.github.io" # the base hostname & protocol for your site
# host: 0.0.0.0

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /blog/:slug
timezone: Asia/Hong_Kong
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

Blog: /blog

# Add general links to site pages here
links:
 About: /about
  # Resume: /assets/resume.pdf
  

# Add links for more focus here
special_links:
  # "Search": https://duckduckgo.com
